### ISSUE TITLE
Special characters in Dropbox filenames

### ISSUE THREAD

**Issue by jacobbudin** [tijsverkoyen/Dropbox#2]
The `filesGet()` method downloads the Dropbox 404 page when requesting files with spaces, and causes internal server errors with commas, in their filenames.

**Comment by tijsverkoyen** [comment]
Hi Jacob,
I tested this, and I don't get any errors. (filename was: `hàh@, $.txt`)

**Comment by jacobbudin** [comment]
The headers (output via `var_dump()`) sent to Dropbox in **your version (v1.0.3)**:

```
array(2) {
  [0]=>
  string(348) "Authorization: OAuth realm="https://api-content.dropbox.com/0/files/dropbox/Popsicle/hàh@, $.txt", oauth_consumer_key="???",oauth_nonce="???",oauth_timestamp="1305680529",oauth_token="???",oauth_signature_method="HMAC-SHA1",oauth_version="1.0",oauth_signature="6dJHjVn%2BhmwjzB0I4FRNDp4wTBU%3D""
  [1]=>
  string(7) "Expect:"
}
```

I receive Dropbox's HTML 404 page.

---

In **my modified version**:

```
array(2) {
  [0]=>
  string(356) "Authorization: OAuth realm="https://api-content.dropbox.com/0/files/dropbox/Popsicle/h%C3%A0h%40%2C%20%24.txt", oauth_consumer_key="???",oauth_nonce="???",oauth_timestamp="1305680770",oauth_token="???",oauth_signature_method="HMAC-SHA1",oauth_version="1.0",oauth_signature="LSQeTswGX4f3ibAYJiHwQHKKdEI=""
  [1]=>
  string(7) "Expect:"
}
```

I receive the text document.

---

In a nutshell, I modified `calculateBaseString()` to return the string _and_ a modified URL (via an array using `list()`) that used your chunking with `rawurlencode()`. The modified URL is then used in `doCall` subsequent to calculating the base string.

I can send you my version if you'd like, so you can run a `diff` on it. I don't want to push a commit, because it's a "quick fix" and doesn't resemble your coding style. I'm sure you could implement it better. For reference, my system:

```
Mac OS X 10.6.7, Apache 2.2.17, PHP 5.3.4
```

**Comment by tijsverkoyen** [comment]
Hi Jacob.
I released a new version (1.0.5). In this version I can't reproduce this issue (tested on PHP 5.2.6 and PHP 5.3.5).

**Comment by Nostrils** [comment]
I'm getting the following when trying to open a folder with a space in the name
 PHP Fatal error:  Uncaught exception 'DropboxException' with message 'Invalid signature. Expected signature base string: GET&https%3A%2F%2Fapi.dropbox.com%2F0%2Fmetadata%2Fdropbox%2FPhotos%2Fsome%2520folder&file_limit%3D1000%26list%3Dtrue%26oauth_consumer_key%3D###%26oauth_nonce%3D###%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1307410558%26oauth_token%3D###%26oauth_version%3D1.0' in /home/folder/dropbox.php:571

Files with spaces in their names give similar results.
It may or may not be related.  It may have something to do with the " " appearing as %2520 instead of %20

To add to the issue any files I try to download have their contents corrupted, even text files. There is no issue viewing the contents of folders.
This is on php 5.2.14

**Comment by tijsverkoyen** [comment]
@Nostrills: I just fixed the issue, see: https://github.com/tijsverkoyen/Dropbox
